# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  buildConfiguration: 'Default'
  redisRepo: 'redis'
  frontRepo: 'azure-vote-front'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'secret'
  vmImage: 'ubuntu-latest'
  dockerRegistryServiceConnection: 'f9e505be-244e-4b73-8410-404aa83e4cb5'


trigger:
- main

pool:
  vmImage: $(vmImage)

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build

    steps:
    - task: Docker@2
      inputs:
        command: buildAndPush
        buildContext: $(Build.Repository.LocalPath)
        repository: $(frontRepo)
        dockerfile: '$(Build.SourcesDirectory)/azure-vote/Dockerfile'
        containerRegistry: 'Container Registry Connection2'
        tags: |
          $(tag)
    - publish: '$(Build.SourcesDirectory)/manifests'
      artifact: manifests
      

- stage: 'Deploy'
  displayName: 'Deploy the containers'
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: 'DemoVotingApp.mydemo'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: manifests
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              kubernetesServiceConnection: 'Kubernetes Cluster Connection'
              namespace: 'mydemo'
              manifests: |
                $(Pipeline.Workspace)/manifests/azure-vote-all-in-one-redis.yaml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                acrdemoakscicd.azurecr.io/$(redisRepo):$(tag)
                acrdemoakscicd.azurecr.io/$(frontRepo):$(tag)
