trigger: none

variables:
  buildConfiguration: 'Release'
  backRepository: 'redis'
  frontRepository: 'azure-vote-front'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'secret'

stages:
- stage: 'Build'
  displayName: 'Build and push'
  jobs:  
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
    - task: dependency-check-build-task@5
      displayName: 'OWASP Dependency Check scan of third-party dependencies' # This task will perform security scan of third-party dependencies
      inputs:
        projectName: 'test'
        scanPath: '$(Build.SourcesDirectory)'
        failOnCVSS: 8 # Fail the build if vulnerabilities with CVSS score higher than 8 are discovered
        format: 'HTML, JUNIT' # Format of scan result report
        enableExperimental: true # Enable experimental file type analyzers
        dependencyCheckVersion: '6.1.6'

    - task: Docker@2
      displayName: 'Build and push the front img to container registry'
      inputs:
        command: buildAndPush
        buildContext: $(Build.Repository.LocalPath)
        repository: $(frontRepository)
        dockerfile: '$(Build.SourcesDirectory)/azure-vote/Dockerfile'
        containerRegistry: 'Container Registry Connection'
        tags: |
          $(tag)
    - publish: '$(Build.SourcesDirectory)/manifests'
      artifact: manifests
- stage: 'Deploy'
  displayName: 'Deploy the containers'
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-20.04'
    environment: 'Voting.default'
    variables:
    - group: Release
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: manifests
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: 'Container Registry Connection'
              kubernetesServiceConnection: 'Kubernetes Cluster Connection'
              namespace: 'default'
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              kubernetesServiceConnection: 'Kubernetes Cluster Connection'
              namespace: 'default'
              manifests: |
                $(Pipeline.Workspace)/manifests/deployment.yml
                $(Pipeline.Workspace)/manifests/service.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(RegistryName)/$(backRepository):$(tag)
                $(RegistryName)/$(frontRepository):$(tag)